import Head from 'next/head'
import Footer from '../components/Footer/Footer'
import { IndexLayout } from '../components/HomPageLayout/IndexLayout'
import { Services } from '../components/HomPageLayout/Services'
import TechStack from '../components/HomPageLayout/TechStack'
import { NavBarIndex } from '../components/Nav/NavBarIndex'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Xessive Observer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBarIndex />
      <IndexLayout />
      <h1>Services</h1>
      <Services />
      <h1>Tech Stack</h1>
      <TechStack />
      <Footer />
    </div>
  )
}
