import Head from 'next/head'
import { HomeHero } from '../components/HomPage/HomeHero'
import { Services } from '../components/HomPage/Services'
import TechStack from '../components/HomPage/TechStack'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Xessive Observer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHero />
      <h1>Services</h1>
      <Services />
      <h1>Tech Stack</h1>
      <TechStack />
    </div>
  )
}
